version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_crud
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

#  crud:
#    build: .
#    container_name: node_crud
#    restart: always
#    environment:
#      DB_HOST: mysql
#      DB_USER: user
#      DB_PASSWORD: password
#      DB_NAME: crud_db
#    ports:
#      - "3000:3000"
#    depends_on:
#      - mysql

volumes:
  mysql_data:
